#!/bin/sh

case "$1" in
  start)
    sleep 20
    if [ nao = `whoami` ]; then
      touch /home/nao/nao.test
      cd /home/nao/Player
      /usr/bin/screen -d -m /usr/local/bin/lua run_vision.lua > /tmp/vision_debug.txt
    else
      su -c 'cd /home/nao/Player; /usr/bin/screen -d -m /usr/local/bin/lua run_vision.lua' - nao
    fi
    ;;
esac

exit 0
