#!/bin/sh

# On Linux, need to verify that xterm is not setgid
# Otherwise, LD_LIBRARY_PATH gets unset in xterm

COMPUTER=`uname`
export COMPUTER

#exec xterm -e "lua -l controller"
#exec luajit -l controller start_dodging.lua
exec lua -l controller start_dodging.lua

